Card/src/java/com/ev/Bingo/bus/dto/usersDTO.java
package com.ev.Bingo.bus.dto;

import com.ev.Bingo.base.dto.BaseDTO;
import java.util.Date;
import java.io.Serializable;

public class usersDTO extends BaseDTO implements usersDTOInter,Serializable,Cloneable  {

    private Boolean boollockedstate;
    private int lockedstate;
    private String showdashboard;
    private Boolean showexportB;
    private Boolean showcorrectineentryB;
    private int profileid;
    private String Profilename;
    private Boolean notificationB;
    private Boolean errorsB;
    private Boolean onlineuserB;
    private int userid;
    private String username;
    private String useraname;
    private int userlang;
    private int holidayenabled;
    private String logonname;
    private String userpassword;
    private int shiftid;
    private int emrholidayenabled;
    private int disputegraph;
    private int shownewatms;
    private int visible;
    private int seeunvisible;
    private int changeotheruserpassword;
    private int restrected;
    private int seerestrected;
    private int status;
    private int showpendingatms;
    private int shownotifications;
    private int showerrors;
    private int showonlineuser;
    private int showexport;
    private int showcorrectiveentry;

    @Override
    public Boolean getBoollockedstate() {
        return boollockedstate;
    }

    @Override
    public void setBoollockedstate(Boolean boollockedstate) {
        this.boollockedstate = boollockedstate;
    }

    @Override
    public int getLockedstate() {
        return lockedstate;
    }

    @Override
    public void setLockedstate(int lockedstate) {
        this.lockedstate = lockedstate;
    }

    @Override
    public String getShowdashboard() {
        return showdashboard;
    }

    @Override
    public void setShowdashboard(String showdashboard) {
        this.showdashboard = showdashboard;
    }

    @Override
    public Boolean getShowexportB() {
        return showexportB;
    }

    @Override
    public void setShowexportB(Boolean showexportB) {
        this.showexportB = showexportB;
    }

    @Override
    public Boolean getShowcorrectineentryB() {
        return showcorrectineentryB;
    }

    @Override
    public void setShowcorrectineentryB(Boolean showcorrectineentryB) {
        this.showcorrectineentryB = showcorrectineentryB;
    }

    @Override
    public int getProfileid() {
        return profileid;
    }

    @Override
    public void setProfileid(int profileid) {
        this.profileid = profileid;
    }

    @Override
    public String getProfilename() {
        return Profilename;
    }

    @Override
    public void setProfilename(String Profilename) {
        this.Profilename = Profilename;
    }

    @Override
    public Boolean getNotificationB() {
        return notificationB;
    }

    @Override
    public void setNotificationB(Boolean notificationB) {
        this.notificationB = notificationB;
    }

    @Override
    public Boolean getErrorsB() {
        return errorsB;
    }

    @Override
    public void setErrorsB(Boolean errorsB) {
        this.errorsB = errorsB;
    }

    @Override
    public Boolean getOnlineuserB() {
        return onlineuserB;
    }

    @Override
    public void setOnlineuserB(Boolean onlineuserB) {
        this.onlineuserB = onlineuserB;
    }

    @Override
    public int getUserid() {
        return userid;
    }

    @Override
    public void setUserid(int userid) {
        this.userid = userid;
    }

    @Override
    public String getUsername() {
        return username;
    }

    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String getUseraname() {
        return useraname;
    }

    @Override
    public void setUseraname(String useraname) {
        this.useraname = useraname;
    }

    @Override
    public int getUserlang() {
        return userlang;
    }

    @Override
    public void setUserlang(int userlang) {
        this.userlang = userlang;
    }

    @Override
    public int getHolidayenabled() {
        return holidayenabled;
    }

    @Override
    public void setHolidayenabled(int holidayenabled) {
        this.holidayenabled = holidayenabled;
    }

    @Override
    public String getLogonname() {
        return logonname;
    }

    @Override
    public void setLogonname(String logonname) {
        this.logonname = logonname;
    }

    @Override
    public String getUserpassword() {
        return userpassword;
    }

    @Override
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }

    @Override
    public int getShiftid() {
        return shiftid;
    }

    @Override
    public void setShiftid(int shiftid) {
        this.shiftid = shiftid;
    }

    @Override
    public int getEmrholidayenabled() {
        return emrholidayenabled;
    }

    @Override
    public void setEmrholidayenabled(int emrholidayenabled) {
        this.emrholidayenabled = emrholidayenabled;
    }

    @Override
    public int getDisputegraph() {
        return disputegraph;
    }

    @Override
    public void setDisputegraph(int disputegraph) {
        this.disputegraph = disputegraph;
    }

    @Override
    public int getShownewatms() {
        return shownewatms;
    }

    @Override
    public void setShownewatms(int shownewatms) {
        this.shownewatms = shownewatms;
    }

    @Override
    public int getVisible() {
        return visible;
    }

    @Override
    public void setVisible(int visible) {
        this.visible = visible;
    }

    @Override
    public int getSeeunvisible() {
        return seeunvisible;
    }

    @Override
    public void setSeeunvisible(int seeunvisible) {
        this.seeunvisible = seeunvisible;
    }

    @Override
    public int getChangeotheruserpassword() {
        return changeotheruserpassword;
    }

    @Override
    public void setChangeotheruserpassword(int changeotheruserpassword) {
        this.changeotheruserpassword = changeotheruserpassword;
    }

    @Override
    public int getRestrected() {
        return restrected;
    }

    @Override
    public void setRestrected(int restrected) {
        this.restrected = restrected;
    }

    @Override
    public int getSeerestrected() {
        return seerestrected;
    }

    @Override
    public void setSeerestrected(int seerestrected) {
        this.seerestrected = seerestrected;
    }

    @Override
    public int getStatus() {
        return status;
    }

    @Override
    public void setStatus(int status) {
        this.status = status;
    }

    @Override
    public int getShowpendingatms() {
        return showpendingatms;
    }

    @Override
    public void setShowpendingatms(int showpendingatms) {
        this.showpendingatms = showpendingatms;
    }

    @Override
    public int getShownotifications() {
        return shownotifications;
    }

    @Override
    public void setShownotifications(int shownotifications) {
        this.shownotifications = shownotifications;
    }

    @Override
    public int getShowerrors() {
        return showerrors;
    }

    @Override
    public void setShowerrors(int showerrors) {
        this.showerrors = showerrors;
    }

    @Override
    public int getShowonlineuser() {
        return showonlineuser;
    }

    @Override
    public void setShowonlineuser(int showonlineuser) {
        this.showonlineuser = showonlineuser;
    }

    @Override
    public int getShowexport() {
        return showexport;
    }

    @Override
    public void setShowexport(int showexport) {
        this.showexport = showexport;
    }

    @Override
    public int getShowcorrectiveentry() {
        return showcorrectiveentry;
    }

    @Override
    public void setShowcorrectiveentry(int showcorrectiveentry) {
        this.showcorrectiveentry = showcorrectiveentry;
    }

}

Card/web/BingoLog.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Bingo Log</title>

        <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/custom-theme/jquery-ui-1.8.1.custom.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/css3.css" />
     
        <style>
            .ui-datatable .ui-datatable-footer{
                background: none;
                background-color: #e6e6e6
            }
            label{
                width:10px;
                text-align: left;
                border: none;
                font-size: 12px
            }
            #rd table td{
                border: none;
            }
        </style>
    </h:head>
    <h:body style="background: none" >
        <h:form id="form1">
            <p:growl id="growl1"  autoUpdate="true" />
            <p:panel header="System Log" id="contentPanel">
                <div align="center" style="width:100%"  >
                    <p:fieldset style="line-height: 35px; margin-top: 15px">
                        <h:panelGrid columns="15" >
                            <h:outputText value="*Date From" />
                            <p style="width: 40px" />
                            
                            <p:calendar pattern="dd.MM.yyyy HH:mm:ss" value="#{BingoLogClient.fromDate}" required="true" requiredMessage="Please Enter Date to Field " />

                            <p style="width: 70px" />

                            <h:outputText value="*Date To" />
                            <p style="width: 40px" />
                            
<p:calendar pattern="dd.MM.yyyy HH:mm:ss" value="#{BingoLogClient.toDate}" required="true" requiredMessage="Please Enter Date to Field " />
                            <p style="width: 70px" />

                            <h:outputText value="User" />
                            <p style="width: 40px" />
                            <h:selectOneMenu value="#{BingoLogClient.userId}" id="users">
                                <f:selectItem itemValue="0" itemLabel="All" />
                                <f:selectItems value="#{BingoLogClient.userList}" var="ms" itemLabel="#{ms.username}" itemValue="#{ms.userid}" />
                            </h:selectOneMenu>
                            <p style="width: 70px" />

                            <h:outputText value="Profile" />
                            <p style="width: 40px" />
                            <h:selectOneMenu value="#{BingoLogClient.profileId}" valueChangeListener="#{BingoLogClient.FilterUsers}">
                                <p:ajax update=":form1:growl1,users" />
                                <f:selectItem itemValue="0" itemLabel="All" />
                                <f:selectItems value="#{BingoLogClient.profileList}" var="ms1" itemLabel="#{ms1.profilename}" itemValue="#{ms1.profileid}" />
                            </h:selectOneMenu>

                        </h:panelGrid>
                        <div align="right">
                           
                            <h:panelGrid columns="4">
                                <p:ajaxStatus style="width:16px;height:16px; margin: 0 0 0 0">
                                    <f:facet name="start">
                                        <h:graphicImage value="../images/ajaxloading.gif" />
                                    </f:facet>
                                    <f:facet name="complete">
                                        <h:outputText value="" />
                                    </f:facet>
                                </p:ajaxStatus>
                                <p:commandButton  update=":form1:growl1,mat_typ_dt,contentPanel" value="Search"  actionListener="#{BingoLogClient.doSearch}" />
                                <p style="width:10px" />
                            </h:panelGrid>
                        </div>
                    </p:fieldset>
                </div>
                <br />
                <p:dataTable   id="mat_typ_dt" paginator="true" rows="10"  value="#{BingoLogClient.logList}" var="ms2">
                    <f:facet name="header">
                        <h:outputText value="Log"/>
                    </f:facet>
                    <p:column headerText="Action Date">
                        <h:outputText escape="false" value="#{ms2.actiondate}"/>
                    </p:column>

                    <p:column headerText="IP Address">
                        <h:outputText  value="#{ms2.ipaddress}"/>
                    </p:column>

                    <p:column headerText="Action">
                        <h:outputText  value="#{ms2.action}"/>
                    </p:column>

                    <p:column headerText="User" style="width: 150px">
                        <h:outputText  value="#{ms2.username}"/>
                    </p:column>

                    <p:column headerText="Profile">
                        <h:outputText  value="#{ms2.profilename}"/>
                    </p:column>
                </p:dataTable><br/>
            </p:panel>
            <!-- Confrim Dialogs -->


        </h:form>
    </h:body>
</html>

Card/web/ChangePassword.xhtml
 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>

        <title>Change Password</title>

        <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/custom-theme/jquery-ui-1.8.1.custom.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/css3.css" />
       

    </h:head>
    <h:body style="background: none" >
        <h:form id="form1">
            <p:panel header="Change Password">
                <p:growl id="growl1"  autoUpdate="true" />
                <div align="center" style="width:100%; padding:  100px 0">
                    <p:panel header="Change Password" style="width:400px; text-align: left">
                        <br />
                        <h:panelGrid columns="3"  style="width:350px" >



                            <h:outputText  value="*Old Password" />
                            <p style="width:10px" />
                            <h:inputSecret required="true" validatorMessage="Required Value"  value="#{ChangePassFroUserClient.oldPass}" />

                            <h:outputText value="*New Password" />
                            <p style="width:10px" />
                            <h:inputSecret value="#{ChangePassFroUserClient.newPass}" />

                            <h:outputText value="*Confirmation Password" />
                            <p style="width:10px" />
                            <h:inputSecret value="#{ChangePassFroUserClient.confPass}" />
                        </h:panelGrid><br />
                        <div style="width:100%">
                           
                            <div align="right">
                                <p:commandButton value="Save" actionListener="#{ChangePassFroUserClient.save}" update=":form1:growl1,idleDialog" />
                            </div>
                        </div>
                        <br/>
                    </p:panel>
                    <p:dialog header="redirect" resizable="false" closable="false" draggable="false" id="idleDialog"
                              widgetVar="idleDialog" modal="true" width="300" styleClass="dialogMonitor"  visible="#{ChangePassFroUserClient.dialogFlag}">
                        <p><a href="Login.xhtml" style="color:blue">click here</a> to relogin</p>
                    </p:dialog>
                </div>
            </p:panel>
        </h:form>

    </h:body>
</html>

Card/web/ColumnsSetup.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Columns Setup</title>

        <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/custom-theme/jquery-ui-1.8.1.custom.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/css3.css" />
    
        <style>
            label{
                width:10px;
                text-align: left;
                border: none;
                font-size: 12px
            }
            #rd table td{
                border: none;
            }
        </style>
    </h:head>
    <h:body style="background: none" >
        <h:form id="form1">
            <p:growl id="growl1"  autoUpdate="true" />
            <p:panel header="Columns Setup" id="content">
                <div align="center">
                    <p:dataTable style="width:600px; "  paginator="true" rows="9" id="mat_typ_dt"  value="#{coloumnsetupclient.cSL}" var="ms"
                                 rowKey="#{ms.id}"   selectionMode="single" selection="#{coloumnsetupclient.selectedrow}">

                        <p:ajax event="rowSelect" listener="#{coloumnsetupclient.onRowSelect}" update=":form1:growl1,:form1:content"   />
                        <f:facet name="header">
                            <h:outputText value="Columns Setup"/>
                        </f:facet>
                         <p:column headerText="*Display Name">
                            <h:inputText value="#{ms.name}"  style="width:150px"/>
                        </p:column>
                     
                        <p:column id="opt" headerText="Action">
                            <p:commandLink  onclick="confirmation.show();" actionListener="#{coloumnsetupclient.fillDelete}" update=":form1:growl1,mat_typ_dt"><p:graphicImage url="images/icons/cross.png" title="delete"  />
                                <f:attribute name="removedRow" value="#{ms}"/>

                            </p:commandLink> 

                        </p:column>

                        <f:facet name="footer">

                            <div align="center" style="height: 20px">
                                <div style="float: right">
                                    <p:commandLink  actionListener="#{coloumnsetupclient.saveAll}" update=":form1:growl1,:form1:mach_typ_dt,mat_typ_dt,:form1:growl1" ><h:graphicImage url="images/icons/pencil.png" title="Save Page" /></p:commandLink>
                                    <p:commandLink actionListener="#{coloumnsetupclient.addcol}"    update=":form1:growl1,:form1:mach_typ_dt,mat_typ_dt,:form1:growl1"  ><h:graphicImage url="images/icons/newmessage.png" title="add new row"  rendered="#{coloumnsetupclient.showAdd}" /></p:commandLink>
                                    <p:commandLink actionListener="#{coloumnsetupclient.confirmAdd}"  update=":form1:growl1,:form1:mach_typ_dt,mat_typ_dt,:form1:growl1"><h:graphicImage url="images/icons/success.png" title="please confirm"  rendered="#{coloumnsetupclient.showConfirm}" /></p:commandLink>
                                </div>
                            </div>
                        </f:facet>
                    </p:dataTable><br/>
                </div>

                <p:confirmDialog widgetVar="confirmation" message="Are you sure you want to delete?" id="confirmation">
                    <p:commandButton value="Yes" onclick="confirmation.hide()"
                                     actionListener="#{coloumnsetupclient.deleteRecord}" update=":form1:growl1,:form1:mach_typ_dt,mat_typ_dt,:form1:growl1" />
                    <p:commandButton value="No" onclick="confirmation.hide()" update=":form1:growl1,mat_typ_dt" />
                </p:confirmDialog>







                <p:dataTable id="mach_typ_dt" value="#{coloumnsetupclient.cSDL}" var="ms1" >
                    <f:facet name="header">
                        <h:outputText value="Column"/>
                    </f:facet>

                    <p:column headerText="Column Name"  >
                        <h:selectOneMenu value="#{ms1.columnid}">
                            <f:selectItems value="#{coloumnsetupclient.fCDL}" var="c" itemLabel="#{c.name}" itemValue="#{c.id}"/>
                        </h:selectOneMenu>
                    </p:column>

                    <p:column id="opt" headerText="Action">
                        <p:commandLink  onclick="confirmation3.show();" actionListener="#{coloumnsetupclient.fillDelete1}" update=":form1:growl1,mach_typ_dt"><p:graphicImage url="images/icons/cross.png" title="delete"  />
                            <f:attribute name="removedRow1" value="#{ms1}"/>
                        </p:commandLink>

                    </p:column>

                    <f:facet name="footer">
                        <div align="center" style="height: 20px">
                            <div style="float: right">
                                <p:commandLink  actionListener="#{coloumnsetupclient.saveAll1}" update=":form1:growl1,:form1:mat_typ_dt,mach_typ_dt,:form1:growl1" ><h:graphicImage url="images/icons/pencil.png" title="Save Page" /></p:commandLink>
                                <p:commandLink actionListener="#{coloumnsetupclient.addcol2}"    update=":form1:growl1,:form1:mat_typ_dt,mach_typ_dt,:form1:growl1"  ><h:graphicImage url="images/icons/newmessage.png" title="add new row"  rendered="#{coloumnsetupclient.showAdd1}" /></p:commandLink>
                                <p:commandLink actionListener="#{coloumnsetupclient.confirmAdd1}"  update=":form1:growl1,:form1:mat_typ_dt,mach_typ_dt,:form1:growl1"><h:graphicImage url="images/icons/success.png" title="please confirm"  rendered="#{coloumnsetupclient.showConfirm1}" /></p:commandLink>
                            </div>
                        </div>
                    </f:facet>
                </p:dataTable><br/>

                <p:confirmDialog widgetVar="confirmation3" message="Are you sure you want to delete?" id="confirmation3">
                    <p:commandButton value="Yes" onclick="confirmation3.hide()"
                                     actionListener="#{coloumnsetupclient.deleteRecord1}" update=":form1:growl1,mach_typ_dt,:form1:growl1" />
                    <p:commandButton value="No" onclick="confirmation3.hide()" update=":form1:growl1,mach_typ_dt" />
                </p:confirmDialog>

            </p:panel>
            <!-- Confrim Dialogs -->


        </h:form>
    </h:body>
</html>

Card/web/EMGHolidays.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Emergency Holidays</title>

        <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/custom-theme/jquery-ui-1.8.1.custom.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/css3.css" />
   

    </h:head>
    <h:body style="background: none" >
        <h:form id="form1">
            <p:panel header="">
                <p:growl id="growl1"  autoUpdate="true" />
                <h:panelGrid columns="3">
                    <h:outputText value="Total Records: " />
                    <p style="width:10px" />
                    <h:outputText value="#{EMGHolidayClient.listSize}" />
                </h:panelGrid>
                <br style="line-height: 3px" />
                <p:dataTable id="EMGHolidays" value="#{EMGHolidayClient.EMGList}" var="ms">
                    <f:facet name="header">
                        <h:outputText value="Emergency  Holidays"/>
                    </f:facet>
                    <p:column headerText="From">
                        <p:calendar showButtonPanel="true"  value="#{ms.pFrom}" valueChangeListener="#{EMGHolidayClient.getOldFDate}"  style="text-align: center" pattern="dd.MM.yyyy"/>

                    </p:column>
                    <p:column headerText="To">
                        <p:calendar showButtonPanel="true"  value="#{ms.pTo}" valueChangeListener="#{EMGHolidayClient.getOldPDate}"  style="text-align: center" pattern="dd.MM.yyyy"/>
                    </p:column>


                    <p:column headerText="English Reason">
                        <h:inputTextarea value="#{ms.eReason}"  style="text-align: center; height: 70px" valueChangeListener="#{EMGHolidayClient.getOldEnglish}"/>
                    </p:column>

                    <p:column headerText="Arabic Reason">
                        <h:inputTextarea value="#{ms.reason}"  style="text-align: center;height: 70px"  valueChangeListener="#{EMGHolidayClient.getOldArabic}"/>
                    </p:column>



                    <p:column headerText="Action">
                        <p:commandLink ajax="true"  onclick="confirmation.show();" actionListener="#{EMGHolidayClient.fillDel}" update=":form1:growl1,display" ><p:graphicImage url="images/icons/cross.png" title="delete"  />
                            <f:attribute name="removedRow" value="#{ms}"/>

                        </p:commandLink> &nbsp;
                        <p:commandLink ajax="true"  actionListener="#{EMGHolidayClient.fillUp}" onclick="confirmation1.show();" update=":form1:growl1,display"><h:graphicImage url="images/icons/pencil.png" title="update" />
                            <f:attribute name="updateRow" value="#{ms}" /></p:commandLink>


                    </p:column>

                    <f:facet name="footer">

                        <div align="center"  style="height: 20px">
                           
                            <div style="float: right">
                                <p:commandLink actionListener="#{EMGHolidayClient.AddEMGHolidays}"    update=":form1:growl1,EMGHolidays"   ><h:graphicImage url="images/icons/newmessage.png" title="add new row"  rendered="#{EMGHolidayClient.showAdd}" /></p:commandLink>
                                <p:commandLink actionListener="#{EMGHolidayClient.ConfirmBlockReason}"  update=":form1:growl1,EMGHolidays"><h:graphicImage url="images/icons/success.png" title="please confirm"  rendered="#{EMGHolidayClient.showConfirm}"/></p:commandLink>
                            </div>
                        </div>
                    </f:facet>
                </p:dataTable><br/>
            </p:panel>
            <p:confirmDialog widgetVar="confirmation" message="Are you sure you want to delete?" id="confirmation" >
                <p:commandButton value="Yes" onclick="confirmation.hide()"
                                 actionListener="#{EMGHolidayClient.deleteEMGHolidays}" update=":form1:growl1,EMGHolidays" />
                <p:commandButton value="No" onclick="confirmation.hide()" update=":form1:growl1,EMGHolidays" actionListener="#{EMGHolidayClient.resetVars}" />
            </p:confirmDialog>

            <p:confirmDialog widgetVar="confirmation1" message="Are you sure you want to update?" id="confirmation1" >
                <p:commandButton value="Yes" onclick="confirmation1.hide()"
                                 actionListener="#{EMGHolidayClient.updateEMGHolidays}" update=":form1:growl1,EMGHolidays" />
                <p:commandButton value="No" onclick="confirmation1.hide()" update=":form1:growl1,EMGHolidays" actionListener="#{EMGHolidayClient.returnOldValues}" />


            </p:confirmDialog>

        </h:form>

    </h:body>
</html>

Card/web/LicenseManagment.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
 
        <title>License Management</title>

        <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/custom-theme/jquery-ui-1.8.1.custom.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="css/css3.css" />
     

    </h:head>
    <h:body style="background: none" >
        <h:form id="form1">
            <p:growl id="growl1"  autoUpdate="true" />
                <p:dataTable id="blockReason" value="#{LicenseManagementClient.myList}" var="ms" rows="13" paginator="true">
                    <f:facet name="header">
                        <h:outputText value="License Management"/>
                    </f:facet>
                    <p:column headerText="ATM" filterBy="#{ms.applicationId}">
                        <h:outputText value="#{ms.applicationId}" style="text-align: center"  />
                    </p:column>
                    <p:column >
                        <p:selectBooleanCheckbox id="status" value="#{ms.LIC}" valueChangeListener="#{LicenseManagementClient.changeValue}" />
                    </p:column>
                </p:dataTable><br/>
                <div align="center" style="height: 20px" >
                 
                    <div style="float: right">
                        <p:commandButton value="Save" actionListener="#{LicenseManagementClient.saveList}"  update=":form1:growl1,display,blockReason" />
                    </div>

                </div>
        </h:form>

    </h:body>
</html>